name: Run Node.js script every 4 hours and push changes

on:
  schedule:
    - cron: '0 */4 * * *'  # This means "every 4 hours"

  # Allows for manual trigger if needed
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set Git user name and email
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install  # Installs npm dependencies

    - name: Run the Node.js script
      run: node .  # Assumes your script is the entry point (index.js or equivalent)
      env:
        COOKIE: ${{ secrets.ROBLOX_COOKIE }}
    - name: Check if there are changes to commit
      run: |
        git diff --exit-code || echo "There are changes to commit"  # Skip if no changes
        git status  # Show status for debugging

    - name: Commit and push changes if any
      run: |
        git add .  # Adds all changes
        git commit -m "Automated changes from script run" || echo "No changes to commit"  # Skip commit if no changes
        git push origin main  # Push to the main branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
